In [4]:
import warnings
import pandas as pd
import pm4py

In [37]:
data = {
    "event_id": ['e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9'],
    "case:concept:name": [1, 1, 1, 1, 2, 2, 2, 3, 3],
    "time:timestamp": pd.to_datetime([
        '2024-01-01 08:00', '2024-01-01 08:15', '2024-01-01 09:00', '2024-01-01 09:30',
        '2024-01-01 08:05', '2024-01-01 08:20', '2024-01-01 10:00',
        '2024-01-02 07:00', '2024-01-02 07:45'
    ]),
    "concept:name":[
        'Register', 'Check', 'Check', 'Approve',
        'Register', 'Approve', 'Close',
        'Register', 'Check'
    ]
}

df = pd.DataFrame(data)
df

  event_id  case:concept:name      time:timestamp concept:name
0       e1                  1 2024-01-01 08:00:00     Register
1       e2                  1 2024-01-01 08:15:00        Check
2       e3                  1 2024-01-01 09:00:00        Check
3       e4                  1 2024-01-01 09:30:00      Approve
4       e5                  2 2024-01-01 08:05:00     Register
5       e6                  2 2024-01-01 08:20:00      Approve
6       e7                  2 2024-01-01 10:00:00        Close
7       e8                  3 2024-01-02 07:00:00     Register
8       e9                  3 2024-01-02 07:45:00        Check

In [5]:
df = pm4py.read_xes("../data/resource.xes")

/Users/bd/Projects/thesis/.venv/lib/python3.12/site-packages/pm4py/utils.py:1027: UserWarning: Install the optional requirement `r4pm` to import/export files faster. `rustxes` remains supported as a fallback.
  warnings.warn(
/Users/bd/Projects/thesis/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
parsing log, completed traces :: 100%|█████████████████████████████████████████████████████████████████████████████████████| 4386/4386 [00:00<00:00, 18784.38it/s]

In [38]:
dt = pd.to_datetime("2024-01-01 08:00")
dt
#type(dt)

Timestamp('2024-01-01 08:00:00')

In [6]:
df = df.sort_values(["time:timestamp"])
df

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,case:concept:name,case:amount,case:region
0,evt_00000001,b,2020-01-01 00:00:00+00:00,2020-01-01 00:30:21.607462+00:00,30.360124,res_01,case_000001,1012.32,region_3
1,evt_00000002,c,2020-01-01 00:32:00.617436+00:00,2020-01-01 01:01:56.277398+00:00,29.927666,res_07,case_000001,1012.32,region_3
2,evt_00000003,d,2020-01-01 01:15:52.002940+00:00,2020-01-01 01:31:01.632015+00:00,15.160485,res_07,case_000001,1012.32,region_3
3,evt_00000004,e,2020-01-01 01:57:43.968071+00:00,2020-01-01 02:47:45.234771+00:00,50.021112,res_03,case_000001,1012.32,region_3
4,evt_00000005,f,2020-01-01 03:02:37.524805+00:00,2020-01-01 03:35:11.198144+00:00,32.561222,res_08,case_000001,1012.32,region_3
...,...,...,...,...,...,...,...,...,...
17632,evt_00017633,f,2020-12-30 23:24:45.706742+00:00,2020-12-30 23:51:34.316798+00:00,26.810168,res_07,case_004385,1019.88,region_3
17634,evt_00017635,c,2020-12-30 23:37:55.095894+00:00,2020-12-31 00:12:25.913586+00:00,34.513628,res_04,case_004386,948.85,region_3
17635,evt_00017636,d,2020-12-31 00:22:42.388434+00:00,2020-12-31 00:48:54.397817+00:00,26.200156,res_07,case_004386,948.85,region_3
17636,evt_00017637,e,2020-12-31 01:19:56.357862+00:00,2020-12-31 02:04:50.299811+00:00,44.899032,res_03,case_004386,948.85,region_3
17637,evt_00017638,f,2020-12-31 02:08:34.602892+00:00,2020-12-31 02:38:03.984951+00:00,29.489701,res_07,case_004386,948.85,region_3

In [7]:
activity_dummies = pd.get_dummies(df['concept:name'], prefix='count')
activity_dummies
#type(activity_dummies)

       count_a  count_b  count_c  count_d  count_e  count_f  count_g  count_h
0        False     True    False    False    False    False    False    False
1        False    False     True    False    False    False    False    False
2        False    False    False     True    False    False    False    False
3        False    False    False    False     True    False    False    False
4        False    False    False    False    False     True    False    False
...        ...      ...      ...      ...      ...      ...      ...      ...
17632    False    False    False    False    False     True    False    False
17634    False    False     True    False    False    False    False    False
17635    False    False    False     True    False    False    False    False
17636    False    False    False    False     True    False    False    False
17637    False    False    False    False    False     True    False    False

[17638 rows x 8 columns]

In [8]:
c_idx_series = df['case:concept:name']
c_idx_series

0        case_000001
1        case_000001
2        case_000001
3        case_000001
4        case_000001
            ...
17632    case_004385
17634    case_004386
17635    case_004386
17636    case_004386
17637    case_004386
Name: case:concept:name, Length: 17638, dtype: str

In [9]:
activity_counts = activity_dummies.groupby(c_idx_series).cumsum()
activity_counts

       count_a  count_b  count_c  count_d  count_e  count_f  count_g  count_h
0            0        1        0        0        0        0        0        0
1            0        1        1        0        0        0        0        0
2            0        1        1        1        0        0        0        0
3            0        1        1        1        1        0        0        0
4            0        1        1        1        1        1        0        0
...        ...      ...      ...      ...      ...      ...      ...      ...
17632        0        1        1        1        1        1        0        0
17634        0        1        1        0        0        0        0        0
17635        0        1        1        1        0        0        0        0
17636        0        1        1        1        1        0        0        0
17637        0        1        1        1        1        1        0        0

[17638 rows x 8 columns]

In [10]:
df = pd.concat([df, activity_counts], axis=1)
df

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,case:concept:name,case:amount,case:region,count_a,count_b,count_c,count_d,count_e,count_f,count_g,count_h
0,evt_00000001,b,2020-01-01 00:00:00+00:00,2020-01-01 00:30:21.607462+00:00,30.360124,res_01,case_000001,1012.32,region_3,0,1,0,0,0,0,0,0
1,evt_00000002,c,2020-01-01 00:32:00.617436+00:00,2020-01-01 01:01:56.277398+00:00,29.927666,res_07,case_000001,1012.32,region_3,0,1,1,0,0,0,0,0
2,evt_00000003,d,2020-01-01 01:15:52.002940+00:00,2020-01-01 01:31:01.632015+00:00,15.160485,res_07,case_000001,1012.32,region_3,0,1,1,1,0,0,0,0
3,evt_00000004,e,2020-01-01 01:57:43.968071+00:00,2020-01-01 02:47:45.234771+00:00,50.021112,res_03,case_000001,1012.32,region_3,0,1,1,1,1,0,0,0
4,evt_00000005,f,2020-01-01 03:02:37.524805+00:00,2020-01-01 03:35:11.198144+00:00,32.561222,res_08,case_000001,1012.32,region_3,0,1,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17632,evt_00017633,f,2020-12-30 23:24:45.706742+00:00,2020-12-30 23:51:34.316798+00:00,26.810168,res_07,case_004385,1019.88,region_3,0,1,1,1,1,1,0,0
17634,evt_00017635,c,2020-12-30 23:37:55.095894+00:00,2020-12-31 00:12:25.913586+00:00,34.513628,res_04,case_004386,948.85,region_3,0,1,1,0,0,0,0,0
17635,evt_00017636,d,2020-12-31 00:22:42.388434+00:00,2020-12-31 00:48:54.397817+00:00,26.200156,res_07,case_004386,948.85,region_3,0,1,1,1,0,0,0,0
17636,evt_00017637,e,2020-12-31 01:19:56.357862+00:00,2020-12-31 02:04:50.299811+00:00,44.899032,res_03,case_004386,948.85,region_3,0,1,1,1,1,0,0,0
17637,evt_00017638,f,2020-12-31 02:08:34.602892+00:00,2020-12-31 02:38:03.984951+00:00,29.489701,res_07,case_004386,948.85,region_3,0,1,1,1,1,1,0,0

In [11]:
# Direcctly follows counts

In [12]:
df['prev_activity'] = df.groupby('case:concept:name')['concept:name'].shift(1)
df

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,case:concept:name,case:amount,case:region,count_a,count_b,count_c,count_d,count_e,count_f,count_g,count_h,prev_activity
0,evt_00000001,b,2020-01-01 00:00:00+00:00,2020-01-01 00:30:21.607462+00:00,30.360124,res_01,case_000001,1012.32,region_3,0,1,0,0,0,0,0,0,NaN
1,evt_00000002,c,2020-01-01 00:32:00.617436+00:00,2020-01-01 01:01:56.277398+00:00,29.927666,res_07,case_000001,1012.32,region_3,0,1,1,0,0,0,0,0,b
2,evt_00000003,d,2020-01-01 01:15:52.002940+00:00,2020-01-01 01:31:01.632015+00:00,15.160485,res_07,case_000001,1012.32,region_3,0,1,1,1,0,0,0,0,c
3,evt_00000004,e,2020-01-01 01:57:43.968071+00:00,2020-01-01 02:47:45.234771+00:00,50.021112,res_03,case_000001,1012.32,region_3,0,1,1,1,1,0,0,0,d
4,evt_00000005,f,2020-01-01 03:02:37.524805+00:00,2020-01-01 03:35:11.198144+00:00,32.561222,res_08,case_000001,1012.32,region_3,0,1,1,1,1,1,0,0,e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17632,evt_00017633,f,2020-12-30 23:24:45.706742+00:00,2020-12-30 23:51:34.316798+00:00,26.810168,res_07,case_004385,1019.88,region_3,0,1,1,1,1,1,0,0,e
17634,evt_00017635,c,2020-12-30 23:37:55.095894+00:00,2020-12-31 00:12:25.913586+00:00,34.513628,res_04,case_004386,948.85,region_3,0,1,1,0,0,0,0,0,b
17635,evt_00017636,d,2020-12-31 00:22:42.388434+00:00,2020-12-31 00:48:54.397817+00:00,26.200156,res_07,case_004386,948.85,region_3,0,1,1,1,0,0,0,0,c
17636,evt_00017637,e,2020-12-31 01:19:56.357862+00:00,2020-12-31 02:04:50.299811+00:00,44.899032,res_03,case_004386,948.85,region_3,0,1,1,1,1,0,0,0,d
17637,evt_00017638,f,2020-12-31 02:08:34.602892+00:00,2020-12-31 02:38:03.984951+00:00,29.489701,res_07,case_004386,948.85,region_3,0,1,1,1,1,1,0,0,e